### ISSUE TITLE
'run dev' error

### ISSUE THREAD

**Issue by estebandres** [code-mcx/vue-mango-music#1]
Hello, first I want to thank you for sharing this content it's a great source for learning.
After running `npm install` I tried to execute the project locally by doing
`npm run dev` however I get this error.
`* @/components/loading/Loading in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/detail/Detail.vue, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/ranking/Ranking.vue and 3 others`
Have you any idea on how to fix the problem?

**Comment by dxx** [comment]
I am sorry about that reply so late, i just saw your issue.
I suggest you use node 8+, babel 6.x and see is babel version compatible with babel-loader version.
After running  `npm install` , all of the package should match the version which in `package.json`
